import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { prisma } from '../utils/prismaClient';
// 1. Import the User type generated by Prisma
import { Router } from 'express';
import { User } from '@prisma/client'; 

// Extend Express Request type to include the full Prisma User type (or a relevant subset)
// Making it optional because it's not present on all requests initially.
export interface AuthRequest extends Request {
  // 2. Change the user type to match what Passport/Prisma provides
  user?: User;
}

// The 'protect' function remains largely the same, but the type system is now consistent
export const protect = async (req: AuthRequest, res: Response, next: NextFunction) => {
  let token: string | undefined;

  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      if (!token) {
        return res.status(401).json({ message: 'Not authorized, no token' });
      }

      const jwtSecret = process.env.JWT_SECRET;
      if (!jwtSecret) {
        // Log the error server-side but send a generic message
        console.error('JWT_SECRET not configured on the server.');
        return res.status(500).json({ message: 'Server configuration error.'}); 
      }

      // Verify the token using the secret
      const decoded = jwt.verify(token, jwtSecret) as { id: number };

      // 3. Fetch the FULL user object using the ID from the token
      const user = await prisma.user.findUnique({
        where: { id: decoded.id },
        // No 'select' needed here, fetch the whole user object
      });

      if (!user) {
        return res.status(401).json({ message: 'Not authorized, user not found' });
      }

      // 4. Attach the full user object to req.user
      req.user = user; 
      next(); // Proceed to the next middleware or route handler

    } catch (error: any) {
      console.error('Token verification/User fetch error in protect middleware:', error);
       // Handle specific JWT errors
      if (error.name === 'JsonWebTokenError') {
           return res.status(401).json({ message: 'Not authorized, invalid token' });
      }
      if (error.name === 'TokenExpiredError') {
           return res.status(401).json({ message: 'Not authorized, token expired' });
      }
      // Generic error for other issues
      res.status(401).json({ message: 'Not authorized, token failed' });
    }
  } else {
    // No token provided in the header
    res.status(401).json({ message: 'Not authorized, no token' });
  }
};
const router = Router();
export default router;
